var fflist = [
	{ffname:'Ackl2004'  , nblist:['Fe', 'P']},
	{ffname:'Alavi2005' , nblist:['H', '-']},
	{ffname:'Amber96'   , nblist:['C', 'Cs', 'F', 'H', '--', 'K', 'Li', 'N', 'O', 'P', 'Rb', 'S', 'Cl']},
	{ffname:'Aqvist'    , nblist:['Ba', 'Ca', 'Cs', 'K', 'Li', 'Mg', 'Na', 'Rb', 'Sr']},
	{ffname:'Belash2006', nblist:['Hg']},
	{ffname:'Belash2013', nblist:['Hg']},
	{ffname:'C19eef1'   , nblist:['C', 'N', 'O', 'S', 'H', 'Fe']},
	{ffname:'C19sasa'   , nblist:['C', 'N', 'O', 'S', 'H', 'Fe']},
	{ffname:'C27rigid'  , nblist:['H', 'O']},
	{ffname:'CatlowFaux', nblist:['O', 'Si', 'Al', 'Na', 'H', 'C']},
	{ffname:'Charmm19'  , nblist:['C', 'H', 'N', 'O', 'S']},
	{ffname:'Charmm22'  , nblist:['C', 'H', 'N', 'O', 'Fe', 'S']},
	{ffname:'Charmm22fe', nblist:['C', 'H', 'F']},
	{ffname:'Charmm27'  , nblist:['Ca', 'C', 'Cs', 'Cl', 'F', 'H', 'Fe', 'Mg', 'N', 'O', 'P', 'K', 'Na', 'S']},
	{ffname:'Charmm27x' , nblist:[]},
	{ffname:'ClayFF'    , nblist:['H', 'O', 'Si', 'Al', 'Mg', 'Ca', 'Fe', 'Li', 'Na', 'K', 'Cs', 'Ba', 'Cl']},
	{ffname:'COMPASSv1' , nblist:['C', 'H', 'N', 'O', 'P', 'He', 'Ne', 'Ar', 'Kr', 'Xe', 'S', 'Si']},
	{ffname:'Coon1987'  , nblist:['N', 'O']},
	{ffname:'Cui1998'   , nblist:['C']},
	{ffname:'Cui2002'   , nblist:['C']},
	{ffname:'DACNIS-UA' , nblist:['C', 'O']},
	{ffname:'devel'     , nblist:['C', 'N', 'H', 'S', 'O', 'P']},
	{ffname:'Dick1994'  , nblist:['N']},
	{ffname:'Ding1986'  , nblist:['Ge']},
	{ffname:'DREIDING'  , nblist:['H', 'B', 'C', 'N', 'O', 'F', 'Al', 'Si', 'P', 'S', 'Cl', 'Ga', 'Ge', 'As', 'Se', 'Br', 'In', 'Sn', 'Sb', 'Te', 'I', 'Na', 'Ca', 'Fe', 'Zn']},
	{ffname:'Dubb2004'  , nblist:['O', 'C', 'Na', 'Al', 'Si']},
	{ffname:'DWS2001'   , nblist:['BB', 'AA', 'TT', 'CC', 'GG']},
	{ffname:'Elli2002'  , nblist:['C']},
	{ffname:'EPM'       , nblist:['C', 'O']},
	{ffname:'Fris2003'  , nblist:['Si', 'O', 'C']},
	{ffname:'Fris2008'  , nblist:['C']},
	{ffname:'Gala1994'  , nblist:['N', 'F', 'Cl']},
	{ffname:'Gordon'    , nblist:['C']},
	{ffname:'Gromos43A1', nblist:['O', 'N', 'C', 'H', '--', 'S', 'Cu', 'Fe', 'Zn', 'Mg', 'Ca', 'P', 'Ar', 'F', 'Cl', 'Br', 'Na', 'Si']},
	{ffname:'HardSphere', nblist:['hs', 'O', 'H', 'Cl', 'Na', 'tr']},
	{ffname:'Hoyt2003'  , nblist:['Pb', 'Cu']},
	{ffname:'Jaramillo' , nblist:['C', 'H', 'F']},
	{ffname:'KFvBvS'    , nblist:['O', 'Si', 'Al', 'P', 'Na', 'Cl']},
	{ffname:'Last1993'  , nblist:['N']},
	{ffname:'LGM'       , nblist:['Br', 'Cl']},
	{ffname:'LJium'     , nblist:['lj']},
	{ffname:'MCY1976'   , nblist:['H', 'O', '']},
	{ffname:'Mend2003'  , nblist:['Fe']},
	{ffname:'mgmstereo' , nblist:[]},
	{ffname:'MM2'       , nblist:['C', 'H']},
	{ffname:'MMFF94'    , nblist:['C', 'H', 'O', 'N', 'F', 'Cl', 'Br', 'I', 'S', 'Si', 'P', 'Fe', 'Li', 'Na', 'K', 'Zn', 'Ca', 'Cu', 'Mg']},
	{ffname:'Morrow2002', nblist:['C', 'F', 'H', 'N', 'P']},
	{ffname:'NERDv1'    , nblist:['C']},
	{ffname:'NERDv2'    , nblist:['C', 'H', 'S']},
	{ffname:'NERDv3'    , nblist:['C', 'H', 'O', 'S']},
	{ffname:'OPLS-1996' , nblist:['C', 'O', 'N', 'H', 'S', 'Ar', 'Kr', 'Xe', 'Cl', 'Ne', 'He', 'F', 'P', 'Br', 'Li', 'Na', 'K', 'Rb', 'Cs', 'Mg', 'Ca', 'Sr', 'Ba', 'U']},
	{ffname:'OPLS-2001' , nblist:['Br', 'C', 'Cl', 'F', 'H', 'I', 'Li', 'N', 'Na', 'O', 'S']},
	{ffname:'OPLS-aa'   , nblist:['Br', 'C', 'Cl', 'F', 'H', 'I', 'Li', 'N', 'Na', 'O', 'S']},
	{ffname:'OPLS-ua'   , nblist:['C', 'Cl', 'F', 'H', 'Li', 'N', 'O', 'Na', 'S']},
	{ffname:'Pana1989'  , nblist:['Ne', 'Ar', 'Kr', 'Xe']},
	{ffname:'ParkHijazi', nblist:['Cu', 'Au']},
	{ffname:'Potter1997', nblist:['C', 'F', 'H']},
	{ffname:'QMFF-VIII' , nblist:['Br', 'Ca', 'Cl', 'Cs', 'Cu', 'F', 'Fe', 'I', 'K', 'Li', 'Mg', 'Na', 'Rb', 'Zn', 'C', 'H', 'N', 'O', 'P', 'S']},
	{ffname:'Richar1995', nblist:['O', 'N', 'Si', 'Al', 'Li', '-']},
	{ffname:'Shah2004'  , nblist:['N', 'C', 'P', 'F']},
	{ffname:'Shukla1987', nblist:['Ar', 'Kr', 'Xe', 'C', 'N']},
	{ffname:'SKS'       , nblist:['C']},
	{ffname:'Smith1994' , nblist:['Na', 'Cl']},
	{ffname:'SMMKmain'  , nblist:['C']},
	{ffname:'SMMKnaip'  , nblist:['C']},
	{ffname:'SPC-E'     , nblist:['O', 'H']},
	{ffname:'SquareWell', nblist:['Sw']},
	{ffname:'Stil1985'  , nblist:['Si']},
	{ffname:'Sum2003'   , nblist:['C', 'O']},
	{ffname:'Tele1987'  , nblist:['O', 'H']},
	{ffname:'TIP3P'     , nblist:['H', 'O']},
	{ffname:'TIP4P'     , nblist:['H', 'O', '']},
	{ffname:'TIP5P'     , nblist:['H', 'O', '']},
	{ffname:'TraPPE-EH' , nblist:['C', 'O', 'N', '-']},
	{ffname:'TraPPE-UA' , nblist:['Ar', 'C', 'He', 'H', 'O', 'S']},
	{ffname:'TraPPE-UAf', nblist:['C']},
	{ffname:'UFF'       , nblist:['H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne', 'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca', 'Sc', 'Ti', 'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se', 'Br', 'Kr', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Mo', 'Tc', 'Ru', 'Rh', 'Pd', 'Ag', 'Cd', 'In', 'Sn', 'Sb', 'Te', 'I', 'Xe', 'Cs', 'Ba', 'La', 'Ce', 'Pr', 'Nd', 'Pm', 'Sm', 'Eu', 'Gd', 'Tb', 'Dy', 'Ho', 'Er', 'Tm', 'Yb', 'Lu', 'Hf', 'Ta', 'W', 'Re', 'Os', 'Ir', 'Pt', 'Au', 'Hg', 'Tl', 'Pb', 'Bi', 'Po', 'At', 'Rn', 'Fr', 'Ra', 'Ac', 'Th', 'Pa', 'U', 'Np', 'Pu', 'Am', 'Cm', 'Bk', 'Cf', 'Es', 'Fm', 'Md', 'No', 'Lr']},
	{ffname:'Unlu2004'  , nblist:['', 'C', 'Ar', 'N', 'S', 'O', 'H', 'F', 'Cl']},
	{ffname:'Vega1992'  , nblist:['Sw']},
	{ffname:'Vink2001'  , nblist:['Si']},
	{ffname:'Walt2001'  , nblist:['C', 'O', 'H']},
	{ffname:'Weiner1984', nblist:['C', 'H', 'LP', 'N', 'O', 'P', 'S']},
	{ffname:'Weiner1986', nblist:['C', 'H', 'LP', 'N', 'O', 'P', 'S']},
	{ffname:'Wielop1985', nblist:['O', 'C']}
];